import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import TransitionMask from "@/components/transitions/transitionMask";
import Navbar from "@/components/navbar/navbar";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} h-screen w-screen`}>
        {children}
        <TransitionMask />
        <Navbar />
      </body>
    </html>
  );
}
